# System
- alias: "Startup Notification"
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.ios_are
      data:
        message: "Home Assistant restarted"

# Lighting
- alias: 'Chili Lights'
  trigger:
    platform: time
    at: '07:00:00'
  action:
    - service: switch.turn_on
      entity_id: switch.chili_lamp
    - delay: 14:00:00
    - service: switch.turn_off
      entity_id: switch.chili_lamp

- alias: 'Caroline Night'
  trigger:
    platform: time
    at: '18:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.soverom_caroline
        brightness_pct: 60
        color_name: hotpink
    - delay: 01:30:00
    - service: light.turn_off
      data:
        entity_id: light.soverom_caroline
        transition: 1800