### SYSTEM ###
- alias: "Startup Notification"
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.ios_are
      data:
        message: "Home Assistant restarted"
    - service: tts.google_say
      entity_id: media_player.kitchen
      data:
        message: "Home Assistant restarted"

# Chili Lights
- alias: 'Chili Lights'
  trigger:
    platform: time
    at: '07:00:00'
  action:
    - service: switch.turn_on
      entity_id: switch.chili_lamp
    - delay: 14:00:00
    - service: switch.turn_off
      entity_id: switch.chili_lamp