# System
- alias: "Startup Notification"
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.ios_are
      data:
        message: "Home Assistant restarted"

- alias: 'Good Morning'
  trigger:
    platform: time
    at: '07:00:00'
  action:
    - service: notify.ios_are
      data:
        message: "Good morning! It's currently {{states.sensor.dark_sky_summary.state}} and {{states.sensor.dark_sky_temperature.state|round}} degrees in Stavanger. "

# Lighting
- alias: 'Chili Lights'
  trigger:
    platform: time
    at: '07:00:00'
  action:
    - service: switch.turn_on
      entity_id: switch.chili_lamp
    - delay: 14:00:00
    - service: switch.turn_off
      entity_id: switch.chili_lamp

- alias: 'Caroline Night'
  trigger:
    platform: time
    at: '18:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.soverom_caroline
        brightness_pct: 60
        color_name: hotpink
    - delay: 01:30:00
    - service: light.turn_off
      data:
        entity_id: light.soverom_caroline
        transition: 1800

  # Sun Scheduled
- alias: 'Outdoor Sunrise'
  trigger:
    platform: sun
    event: sunrise
    offset: '+00:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: light.ute

- alias: 'Outdoor Sunset'
  trigger:
    platform: sun
    event: sunset
    offset: '+00:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.ute