- platform: template
  sensors:
    projector:
      friendly_name: "Projector"
      icon_template: mdi:projector
      delay_off:
        minutes: 1
      value_template: >-
        {{ states('sensor.projector_effect')|float > 1 }}

- platform: ping
  name: Saturn
  host: !secret synology_host
  count: 1
  scan_interval: 3600