# Core Configuration
homeassistant: !include includes/homeassistant.yaml
default_config:
frontend:
  themes: !include_dir_merge_named themes

automation: !include_dir_merge_list automations/
script: !include scripts.yaml

discovery: !include includes/discovery.yaml
recorder: !include includes/recorder.yaml
person: !include includes/persons.yaml
notify: !include includes/notify.yaml
input_select: !include includes/input_selects.yaml

air_quality: !include includes/air_quality.yaml
binary_sensor: !include includes/binary_sensors.yaml
group: !include includes/groups.yaml
sensor: !include includes/sensors.yaml
light: !include includes/lights.yaml
speedtestdotnet: !include includes/speedtestdotnet.yaml
hue: !include includes/hue.yaml
tts: !include includes/tts.yaml
ios: !include includes/ios.yaml
verisure: !include includes/verisure.yaml
tibber: !include includes/tibber.yaml
plant: !include includes/plants.yaml
apple_tv:
samsungtv: !include includes/samsungtv.yaml

# Custom modules
volkswagencarnet: !include includes/volkswagencarnet.yaml
