background: var(--background-image)
custom_header:
  background: rgba(155, 155, 155, 0.25)
  button_text: {options: '{{ hours24 }}:{{ minutesLZ }}'}
  compact_mode: true
  voice_hide: true
title: Home
views:
- badges:
  - {entity: device_tracker.are}
  - {entity: device_tracker.monica_sin_iphone_2}
  - {entity: device_tracker.passat_gte}
  - {entity: sun.sun}
  cards:
  - {entity: weather.home, type: weather-forecast}
  - cards:
    - cards:
      - entity: light.living_room_lights
        hold_action: {action: more-info}
        icon: mdi:sofa
        icon_height: 40px
        name: Stue
        show_icon: true
        show_name: true
        show_state: false
        tap_action: {action: toggle}
        type: button
      - entity: light.kitchen_lights
        hold_action: {action: more-info}
        icon: mdi:stove
        icon_height: 40px
        name: Kjøkken
        show_icon: true
        show_name: true
        show_state: false
        tap_action: {action: toggle}
        type: button
      - entity: light.hall_lights
        hold_action: {action: more-info}
        icon: mdi:ceiling-light
        icon_height: 40px
        name: Gang
        show_icon: true
        show_name: true
        show_state: false
        tap_action: {action: toggle}
        type: button
      type: horizontal-stack
    - cards:
      - entity: light.bedroom_lights
        hold_action: {action: more-info}
        icon: mdi:bed
        icon_height: 40px
        name: Soverom
        show_icon: true
        show_name: true
        show_state: false
        tap_action: {action: toggle}
        type: button
      - entity: light.soverom_caroline
        hold_action: {action: more-info}
        icon: mdi:bed
        icon_height: 40px
        name: Soverom C
        show_icon: true
        show_name: true
        show_state: false
        tap_action: {action: toggle}
        type: button
      - entity: light.soverom_emilie
        hold_action: {action: more-info}
        icon: mdi:bed
        icon_height: 40px
        name: Soverom E
        show_icon: true
        show_name: true
        show_state: false
        tap_action: {action: toggle}
        type: button
      type: horizontal-stack
    - cards:
      - entity: light.office_lights
        hold_action: {action: more-info}
        icon: mdi:desk
        icon_height: 40px
        name: Kontor
        show_icon: true
        show_name: true
        show_state: false
        tap_action: {action: toggle}
        type: button
      - entity: light.home_theater_lights
        hold_action: {action: more-info}
        icon: mdi:theater
        icon_height: 40px
        name: Kino
        show_icon: true
        show_name: true
        show_state: false
        tap_action: {action: toggle}
        type: button
      - entity: light.guest_room_lights
        hold_action: {action: more-info}
        icon: mdi:bed
        icon_height: 40px
        name: Gjesterom
        show_icon: true
        show_name: true
        show_state: false
        tap_action: {action: toggle}
        type: button
      type: horizontal-stack
    - cards:
      - entity: light.outside_lights
        hold_action: {action: more-info}
        icon: mdi:terrain
        icon_height: 40px
        name: Ute
        show_icon: true
        show_name: true
        show_state: false
        tap_action: {action: toggle}
        type: button
      - entity: input_select.house_mode
        hold_action: {action: more-info}
        icon_height: 40px
        name: Mode
        show_icon: true
        show_name: false
        show_state: true
        tap_action: {action: more-info}
        type: button
      type: horizontal-stack
    type: vertical-stack
  - columns: 6
    entities:
    - {entity: binary_sensor.projector}
    - {entity: media_player.living_room, icon: 'mdi:television'}
    - {entity: binary_sensor.varmepumpe}
    - {entity: binary_sensor.vaskemaskin}
    - {entity: binary_sensor.torketrommel}
    - {entity: binary_sensor.updater}
    show_icon: true
    show_name: false
    show_state: false
    title: Status
    type: glance
  - cards:
    - cards:
      - entities: [sensor.dark_sky_temperature]
        font_size: 75
        name: Ute
        type: custom:mini-graph-card
      type: horizontal-stack
    - cards:
      - entities: [sensor.stue_temperature, sensor.stue_humidity]
        font_size: 75
        name: Stue
        type: custom:mini-graph-card
      - entities: [sensor.kjellerstue_temperature, sensor.kjellerstue_humidity]
        font_size: 75
        name: Kjellerstue
        type: custom:mini-graph-card
      type: horizontal-stack
    - cards:
      - entities: [sensor.kjellergang_temperature, sensor.gang_temperature, sensor.gang_etg_2_temperature]
        font_size: 75
        name: Gang
        type: custom:mini-graph-card
      - entities: [sensor.hovedsoverom_temperature, sensor.barnsoverom_temperature]
        font_size: 75
        name: Soverom
        type: custom:mini-graph-card
      type: horizontal-stack
    type: vertical-stack
  - entities:
    - {entity: sensor.buss_skolebrygga}
    type: entities
  - entities:
    - entities:
      - entities: [sensor.drivhus_watts]
        font_size: 75
        show: {icon: false, name: false}
        type: custom:mini-graph-card
      head: switch.drivhus
      type: custom:fold-entity-row
    - entities:
      - entities: [sensor.fgwpe_f_wall_plug_gen5_power]
        font_size: 75
        show: {icon: false, name: false}
        type: custom:mini-graph-card
      head: switch.kitchen_plant
      type: custom:fold-entity-row
    type: entities
  - entities:
    - {entity: binary_sensor.wvwzzz3czje032810_external_power}
    - {entity: sensor.wvwzzz3czje032810_combustion_range}
    - {entity: sensor.wvwzzz3czje032810_electric_range}
    - {entity: sensor.wvwzzz3czje032810_charging_time_left}
    show_name: false
    title: Passat GTE
    type: glance
  icon: mdi:home
  path: home
  title: Home
- badges: []
  cards:
  - {entity: media_player.kitchen, type: media-control}
  - {entity: media_player.living_room, type: media-control}
  icon: mdi:television-classic
  path: media
  title: Media
- badges: []
  cards:
  - entities:
    - {entity: binary_sensor.stue_sensor_motion}
    - {entity: light.stue}
    - {entity: sensor.stue_temperature}
    - {entity: sensor.stue_humidity}
    - {entity: sensor.stue_sensor_light_level}
    show_icon: true
    show_name: false
    show_state: true
    title: Stue
    type: glance
  - entities:
    - {entity: light.soverom_emilie}
    - {entity: sensor.barnsoverom_temperature}
    - {entity: sensor.barnsoverom_humidity}
    show_name: false
    title: Soverom Emilie
    type: glance
  - entities:
    - {entity: light.soverom_caroline}
    - {entity: sensor.hovedsoverom_temperature}
    - {entity: sensor.hovedsoverom_humidity}
    - {entity: binary_sensor.vindu_hovedsoverom}
    show_name: false
    title: Soverom Caroline
    type: glance
  - entities:
    - {entity: light.gang_inngang}
    - {entity: sensor.entregang_temperature}
    - {entity: sensor.entregang_humidity}
    - {entity: lock.inngangsdor}
    - {entity: binary_sensor.state_main_door}
    show_name: false
    title: Gang Hovedetasje
    type: glance
  - entities:
    - {entity: light.gang_soverom}
    - {entity: sensor.gang_etg_2_temperature}
    - {entity: sensor.gang_etg_2_humidity}
    show_name: false
    title: Gang 2. Etasje
    type: glance
  - entities:
    - {entity: light.gang_kjeller}
    - {entity: sensor.kjellergang_temperature}
    - {entity: sensor.kjellergang_humidity}
    show_name: false
    title: Gang Kjeller
    type: glance
  - entities:
    - {entity: light.kjellerstue}
    - {entity: sensor.kjellerstue_temperature}
    - {entity: sensor.kjellerstue_humidity}
    - {entity: binary_sensor.office_motion}
    show_name: false
    title: Kino
    type: glance
  - entities:
    - {entity: light.kjellerrom}
    - {entity: sensor.basement_air_temperature}
    - {entity: sensor.basement_humidity}
    - {entity: binary_sensor.kjellerdor}
    - {entity: binary_sensor.basement_motion}
    show_name: false
    title: Gjesterom
    type: glance
  - entities:
    - {entity: light.ute}
    - {entity: sensor.dark_sky_temperature}
    - {entity: binary_sensor.state_bod_door}
    show_name: false
    title: Ute
    type: glance
  - entities:
    - {entity: light.kitchen_lights}
    - {entity: sensor.kitchen_temperature}
    - {entity: sensor.kitchen_humidity}
    - {entity: binary_sensor.kitchen_motion}
    show_name: false
    title: Kjøkken
    type: glance
  icon: mdi:monitor-dashboard
  path: monitor
  title: Monitor
- badges: []
  cards:
  - cards:
    - cards:
      - entities: [sensor.real_time_consumption_tostenhagen_54]
        font_size: 75
        name: Strømforbruk
        type: custom:mini-graph-card
      - entities: [sensor.electricity_price_tostenhagen_54]
        font_size: 75
        name: Strømpris
        type: custom:mini-graph-card
      type: horizontal-stack
    - cards:
      - entities: [sensor.house_voltage]
        font_size: 75
        name: Spenning
        type: custom:mini-graph-card
      - entities: [sensor.server_watts]
        font_size: 75
        name: Server
        type: custom:mini-graph-card
      type: horizontal-stack
    - cards:
      - entities: [sensor.torketrommel_watts]
        font_size: 75
        name: Tørketrommel
        type: custom:mini-graph-card
      - entities: [sensor.projector_watts]
        font_size: 75
        name: Projektor
        type: custom:mini-graph-card
      type: horizontal-stack
    - cards:
      - entities: [sensor.vaskemaskin_watts]
        font_size: 75
        name: Vaskemaskin
        type: custom:mini-graph-card
      - entities: [sensor.varmepumpe_watts]
        font_size: 75
        name: Varmepumpe
        type: custom:mini-graph-card
      type: horizontal-stack
    type: vertical-stack
  - entities:
    - sensor.uptime
    - {entity: binary_sensor.pluto}
    - entities:
      - {entity: sensor.processor_use}
      - {entity: sensor.memory_use_percent}
      - {entity: sensor.disk_use_percent_home}
      head: binary_sensor.neptune
      type: custom:fold-entity-row
    - entities: [sensor.saturn_cpu_load_total, sensor.saturn_memory_usage_real, sensor.saturn_volume_1_volume_used]
      head: binary_sensor.saturn
      type: custom:fold-entity-row
    - entities: [sensor.mercury_cpu_load_total, sensor.mercury_memory_usage_real,
        sensor.mercury_volume_1_volume_used]
      head: binary_sensor.mercury
      type: custom:fold-entity-row
    show_header_toggle: false
    title: Network
    type: entities
  - cards:
    - cards:
      - entities: [sensor.pi_hole_dns_queries_today]
        font_size: 75
        name: Total Queries
        type: custom:mini-graph-card
      - entities: [sensor.pi_hole_ads_blocked_today]
        font_size: 75
        name: Queries Blocked
        type: custom:mini-graph-card
      type: horizontal-stack
    - cards:
      - entities: [sensor.pi_hole_ads_percentage_blocked_today]
        font_size: 75
        name: Percent Blocked
        type: custom:mini-graph-card
      - entities: [sensor.pi_hole_domains_blocked]
        font_size: 75
        name: Domains on Blocklist
        type: custom:mini-graph-card
      type: horizontal-stack
    type: vertical-stack
  - entities:
    - {entity: sensor.speedtest_ping}
    - {entity: sensor.speedtest_download}
    - {entity: sensor.speedtest_upload}
    show_header_toggle: false
    title: Internet
    type: entities
  - columns: 2
    entities:
    - {entity: sensor.hours_washing_machine_has_been_on_last_7_days, icon: 'mdi:washing-machine',
      name: Vaskemaskin}
    - {entity: sensor.hours_dryer_has_been_on_last_7_days, icon: 'mdi:tumble-dryer',
      name: Tørketrommel}
    - {entity: sensor.hours_heat_pump_has_been_on_last_7_days, icon: 'mdi:radiator',
      name: Varmepumpe}
    - {entity: sensor.hours_projector_has_been_on_last_7_days, icon: 'mdi:projector',
      name: Projector}
    - {entity: sensor.hours_speakers_has_been_on_last_7_days, icon: 'mdi:television',
      name: Tv}
    - {entity: sensor.hours_charging_has_been_on_last_7_days, icon: 'mdi:battery-charging',
      name: Charging}
    show_name: false
    title: Utilities Stats
    type: glance
  icon: mdi:home-automation
  path: system
  title: System
- badges: []
  cards:
  - {entity: plant.plant_1, name: Tomatplante Drivhus, type: plant-status}
  - {entity: plant.plant_2, name: Tomatplante Kjøkken, type: plant-status}
  - {entity: plant.plant_3, name: Plante Stue, type: plant-status}
  - {entity: plant.plant_4, name: Plante Spisestue, type: plant-status}
  icon: mdi:flower
  path: plants
  title: Plants
