background: var(--background-image)
custom_header:
  background: rgba(155, 155, 155, 0.25)
  button_text: {options: '{{ hours24 }}:{{ minutesLZ }}'}
  compact_mode: true
  voice_hide: true
title: Home
views:
- badges:
  - {entity: person.are_tjora}
  - {entity: person.monica_hansen}
  - {entity: sun.sun}
  cards:
  - {entity: weather.home, type: weather-forecast}
  - entities:
    - entities: [light.hue_ambiance_lamp_1, light.hue_ambiance_lamp_2]
      head: {entity: light.stue, name: Stue, type: 'custom:slider-entity-row'}
      type: custom:fold-entity-row
    - entities: [light.hue_ambiance_lamp_3]
      head: {entity: light.kjokken, name: Kjøkken, type: 'custom:slider-entity-row'}
      type: custom:fold-entity-row
    - entities: [light.hue_color_lamp_1]
      head: {entity: light.soverom, name: Soverom H, type: 'custom:slider-entity-row'}
      type: custom:fold-entity-row
    - entities: [light.hue_color_lamp_4]
      head: {entity: light.soverom_caroline, name: Soverom C, type: 'custom:slider-entity-row'}
      type: custom:fold-entity-row
    - entities: [light.hue_white_lamp_1, light.hue_white_lamp_2]
      head: {entity: light.gang_inngang, name: Inngang, type: 'custom:slider-entity-row'}
      type: custom:fold-entity-row
    - entities: [light.hue_white_lamp_4]
      head: {entity: light.gang_soverom, name: Gang 2.etg, type: 'custom:slider-entity-row'}
      type: custom:fold-entity-row
    - entities: [light.hue_white_lamp_3]
      head: {entity: light.gang_kjeller, name: Gang Kjeller, type: 'custom:slider-entity-row'}
      type: custom:fold-entity-row
    - entities: [light.hue_color_lamp_2, light.hue_color_lamp_3, light.hue_lightstrip_plus_1]
      head: {entity: light.kjellerstue, name: Kjellerstue, type: 'custom:slider-entity-row'}
      type: custom:fold-entity-row
    - entities: [light.hue_white_lamp_8, light.hue_white_lamp_7, light.hue_white_lamp_6,
        light.hue_white_lamp_5]
      head: {entity: light.ute, name: Ute, type: 'custom:slider-entity-row'}
      type: custom:fold-entity-row
    show_header_toggle: false
    title: Lys
    type: entities
  - cards:
    - cards:
      - entities: [sensor.stue_temperature, sensor.stue_humidity]
        font_size: 75
        name: Stue
        type: custom:mini-graph-card
      - entities: [sensor.kjellerstue_temperature, sensor.kjellerstue_humidity]
        font_size: 75
        name: Kjellerstue
        type: custom:mini-graph-card
      type: horizontal-stack
    - cards:
      - entities: [sensor.kjellergang_temperature, sensor.gang_temperature, sensor.gang_etg_2_temperature]
        font_size: 75
        name: Gang
        type: custom:mini-graph-card
      - entities: [sensor.hovedsoverom_temperature, sensor.barnsoverom_temperature]
        font_size: 75
        name: Soverom
        type: custom:mini-graph-card
      type: horizontal-stack
    type: vertical-stack
  - columns: 5
    entities:
    - {entity: binary_sensor.cinema}
    - {entity: binary_sensor.projector}
    - {entity: binary_sensor.varmepumpe}
    - {entity: binary_sensor.updater}
    - {entity: binary_sensor.motion_detected_last_hour}
    show_icon: true
    show_name: false
    show_state: false
    title: Status
    type: glance
  - entities:
    - entities:
      - entities: [sensor.drivhus_effect]
        font_size: 75
        show: {icon: false, name: false}
        type: custom:mini-graph-card
      head: switch.drivhus
      type: custom:fold-entity-row
    type: entities
  - entities:
    - {entity: sensor.buss_skolebrygga}
    type: entities
  - columns: 4
    entities:
    - {entity: sensor.wvwzzz3czje032810_battery_level}
    - {entity: sensor.wvwzzz3czje032810_fuel_level}
    - {entity: sensor.wvwzzz3czje032810_charging_time_left}
    - {entity: sensor.wvwzzz3czje032810_odometer}
    - {entity: sensor.wvwzzz3czje032810_electric_range}
    - {entity: sensor.wvwzzz3czje032810_combustion_range}
    - {entity: sensor.wvwzzz3czje032810_combined_range}
    - {entity: binary_sensor.wvwzzz3czje032810_external_power}
    show_name: false
    title: Passat GTE
    type: glance
  icon: mdi:home
  path: home
  title: Home
- badges: []
  cards:
  - {entity: media_player.kitchen, type: media-control}
  - {entity: media_player.living_room, type: media-control}
  - entity: binary_sensor.projector
    hold_action: {action: more-info}
    icon_height: 50px
    name: Home Theater
    show_icon: true
    show_name: true
    tap_action: {action: more-info}
    type: entity-button
  icon: mdi:television-classic
  path: media
  title: Media
- badges: []
  cards:
  - entities:
    - {entity: binary_sensor.stue_sensor_motion}
    - {entity: light.stue}
    - {entity: sensor.stue_temperature}
    - {entity: sensor.stue_humidity}
    - {entity: sensor.stue_sensor_light_level}
    show_icon: true
    show_name: false
    show_state: true
    title: Stue
    type: glance
  - entities:
    - {entity: sensor.barnsoverom_temperature}
    - {entity: sensor.barnsoverom_humidity}
    show_name: false
    title: Soverom Emilie
    type: glance
  - entities:
    - {entity: light.soverom_caroline}
    - {entity: sensor.hovedsoverom_temperature}
    - {entity: sensor.hovedsoverom_humidity}
    - {entity: binary_sensor.vindu_hovedsoverom}
    show_name: false
    title: Soverom Caroline
    type: glance
  - entities:
    - {entity: light.gang_inngang}
    - {entity: sensor.entregang_temperature}
    - {entity: sensor.entregang_humidity}
    - {entity: lock.inngangsdor}
    show_name: false
    title: Gang Hovedetasje
    type: glance
  - entities:
    - {entity: light.gang_soverom}
    - {entity: sensor.gang_etg_2_temperature}
    - {entity: sensor.gang_etg_2_humidity}
    show_name: false
    title: Gang 2. Etasje
    type: glance
  - entities:
    - {entity: light.gang_kjeller}
    - {entity: sensor.kjellergang_temperature}
    - {entity: sensor.kjellergang_humidity}
    show_name: false
    title: Gang Kjeller
    type: glance
  - entities:
    - {entity: light.kjellerstue}
    - {entity: sensor.kjellerstue_temperature}
    - {entity: sensor.kjellerstue_humidity}
    show_name: false
    title: Kino
    type: glance
  - entities:
    - {entity: binary_sensor.vindu_kjellerdor}
    - {entity: binary_sensor.kjellerdor}
    show_name: false
    title: Gjesterom
    type: glance
  - entities:
    - {entity: light.ute}
    - {entity: sensor.dark_sky_temperature}
    show_name: false
    title: Ute
    type: glance
  icon: mdi:monitor-dashboard
  path: monitor
  title: Monitor
- badges: []
  cards:
  - cards:
    - cards:
      - entities: [sensor.house_voltage]
        font_size: 75
        name: Volt
        type: custom:mini-graph-card
      - entities: [sensor.varmepumpe_effect]
        font_size: 75
        name: Varmepumpe
        type: custom:mini-graph-card
      type: horizontal-stack
    - cards:
      - entities: [sensor.kino_effect]
        font_size: 75
        name: Kino
        type: custom:mini-graph-card
      - entities: [sensor.projector_effect]
        font_size: 75
        name: Projector
        type: custom:mini-graph-card
      type: horizontal-stack
    - cards:
      - entities: [sensor.server_effect]
        font_size: 75
        name: Server
        type: custom:mini-graph-card
      - entities: [sensor.electricity_price_tostenhagen_54]
        font_size: 75
        name: Strømpris
        type: custom:mini-graph-card
      type: horizontal-stack
    type: vertical-stack
  - entities:
    - sensor.uptime
    - entities:
      - {entity: sensor.processor_use}
      - {entity: sensor.memory_use_percent}
      - {entity: sensor.disk_use_percent_home}
      head: binary_sensor.neptune
      type: custom:fold-entity-row
    - entities: [sensor.saturn_cpu_load_total, sensor.saturn_memory_usage_real, sensor.saturn_volume_used_volume_2]
      head: binary_sensor.saturn
      type: custom:fold-entity-row
    - entities: [sensor.mercury_cpu_load_total, sensor.mercury_memory_usage_real,
        sensor.mercury_volume_used_volume_1]
      head: binary_sensor.mercury
      type: custom:fold-entity-row
    - entities: [sensor.google_wifi_uptime, sensor.google_wifi_last_restart, sensor.google_wifi_current_version,
        sensor.google_wifi_local_ip]
      head: {entity: sensor.google_wifi_status, name: Google Wifi}
      type: custom:fold-entity-row
    show_header_toggle: false
    title: Network
    type: entities
  - entities:
    - {entity: sensor.speedtest_ping}
    - {entity: sensor.speedtest_download}
    - {entity: sensor.speedtest_upload}
    show_header_toggle: false
    title: Internet
    type: entities
  icon: mdi:home-automation
  path: system
  title: System
- badges: []
  cards:
  - entities: [automation.caroline_night, automation.hall_lights_day, automation.hall_lights_night,
      automation.outdoor_day, automation.outdoor_night, automation.plant_lights_day,
      automation.plant_lights_night, automation.projector_started, automation.projector_stopped]
    title: Automations
    type: entities
  - entities: [automation.startup_notification, automation.morning_notification, automation.car_battery_notification]
    title: Notifications
    type: entities
  icon: mdi:robot
  path: automation
  title: Automation
