background: var(--background-image)
custom_header:
  background: rgba(155, 155, 155, 0.25)
  button_text: {options: '{{ hours24 }}:{{ minutesLZ }}'}
  compact_mode: true
  voice_hide: true
title: Home
views:
- badges:
  - {entity: person.are_tjora}
  - {entity: person.monica_hansen}
  - {entity: sun.sun}
  cards:
  - {entity: weather.home, type: weather-forecast}
  - entities:
    - entities: [light.hue_ambiance_lamp_1, light.hue_ambiance_lamp_2]
      head: {entity: light.stue, icon: 'mdi:sofa', name: Stue, type: 'custom:slider-entity-row'}
      type: custom:fold-entity-row
    - entities: [light.hue_ambiance_lamp_3]
      head: {entity: light.kjokken, icon: 'mdi:fridge-outline', name: Kjøkken, type: 'custom:slider-entity-row'}
      type: custom:fold-entity-row
    - entities: [light.hue_color_lamp_1]
      head: {entity: light.soverom, icon: 'mdi:bed-king', name: Soverom M, type: 'custom:slider-entity-row'}
      type: custom:fold-entity-row
    - entities: [light.hue_color_lamp_4]
      head: {entity: light.soverom_caroline, icon: 'mdi:bed-empty', name: Soverom
          C, type: 'custom:slider-entity-row'}
      type: custom:fold-entity-row
    - entities: [light.hue_white_lamp_1_2]
      head: {entity: light.soverom_emilie, icon: 'mdi:bed-empty', name: Soverom E,
        type: 'custom:slider-entity-row'}
      type: custom:fold-entity-row
    - entities: [light.color_light_1, light.color_temperature_light_1, light.color_temperature_light_2]
      head: {entity: light.kjellerrom, icon: 'mdi:bed-empty', name: Gjesterom, type: 'custom:slider-entity-row'}
      type: custom:fold-entity-row
    - entities: [light.hue_color_lamp_2, light.hue_color_lamp_3, light.hue_lightstrip_plus_1]
      head: {entity: light.kjellerstue, icon: 'mdi:projector-screen', name: Kjellerstue,
        type: 'custom:slider-entity-row'}
      type: custom:fold-entity-row
    - entities: [light.hue_white_lamp_1, light.hue_white_lamp_2, light.hue_white_lamp_4,
        light.hue_white_lamp_3]
      head: {entity: light.outside_lights, icon: 'mdi:home-outline', name: Gang, type: 'custom:slider-entity-row'}
      type: custom:fold-entity-row
    - entities: [light.hue_white_lamp_8, light.hue_white_lamp_7, light.hue_white_lamp_6,
        light.hue_white_lamp_5]
      head: {entity: light.ute, icon: 'mdi:terrain', name: Ute, type: 'custom:slider-entity-row'}
      type: custom:fold-entity-row
    show_header_toggle: false
    title: Lys
    type: entities
  - cards:
    - cards:
      - entities: [sensor.stue_temperature, sensor.stue_humidity]
        font_size: 75
        name: Stue
        type: custom:mini-graph-card
      - entities: [sensor.kjellerstue_temperature, sensor.kjellerstue_humidity]
        font_size: 75
        name: Kjellerstue
        type: custom:mini-graph-card
      type: horizontal-stack
    - cards:
      - entities: [sensor.kjellergang_temperature, sensor.gang_temperature, sensor.gang_etg_2_temperature]
        font_size: 75
        name: Gang
        type: custom:mini-graph-card
      - entities: [sensor.hovedsoverom_temperature, sensor.barnsoverom_temperature]
        font_size: 75
        name: Soverom
        type: custom:mini-graph-card
      type: horizontal-stack
    type: vertical-stack
  - columns: 6
    entities:
    - {entity: media_player.tv_stue}
    - {entity: binary_sensor.projector}
    - {entity: binary_sensor.varmepumpe}
    - {entity: binary_sensor.vaskemaskin}
    - {entity: binary_sensor.torketrommel}
    - {entity: binary_sensor.updater}
    show_icon: true
    show_name: false
    show_state: false
    title: Status
    type: glance
  - entities:
    - entities:
      - entities: [sensor.drivhus_watts]
        font_size: 75
        show: {icon: false, name: false}
        type: custom:mini-graph-card
      head: switch.drivhus
      type: custom:fold-entity-row
    type: entities
  - entities:
    - {entity: sensor.buss_skolebrygga}
    type: entities
  - columns: 4
    entities:
    - {entity: sensor.wvwzzz3czje032810_battery_level}
    - {entity: sensor.wvwzzz3czje032810_fuel_level}
    - {entity: sensor.wvwzzz3czje032810_charging_time_left}
    - {entity: sensor.wvwzzz3czje032810_odometer}
    - {entity: sensor.wvwzzz3czje032810_electric_range}
    - {entity: sensor.wvwzzz3czje032810_combustion_range}
    - {entity: sensor.wvwzzz3czje032810_combined_range}
    - {entity: binary_sensor.wvwzzz3czje032810_external_power}
    show_name: false
    title: Passat GTE
    type: glance
  icon: mdi:home
  path: home
  title: Home
- badges: []
  cards:
  - {entity: media_player.kitchen, type: media-control}
  - {entity: media_player.living_room, type: media-control}
  - {entity: media_player.plex_plex_for_apple_tv_stue, type: media-control}
  icon: mdi:television-classic
  path: media
  title: Media
- badges: []
  cards:
  - entities:
    - {entity: binary_sensor.stue_sensor_motion}
    - {entity: light.stue}
    - {entity: sensor.stue_temperature}
    - {entity: sensor.stue_humidity}
    - {entity: sensor.stue_sensor_light_level}
    show_icon: true
    show_name: false
    show_state: true
    title: Stue
    type: glance
  - entities:
    - {entity: light.soverom_emilie}
    - {entity: sensor.barnsoverom_temperature}
    - {entity: sensor.barnsoverom_humidity}
    show_name: false
    title: Soverom Emilie
    type: glance
  - entities:
    - {entity: light.soverom_caroline}
    - {entity: sensor.hovedsoverom_temperature}
    - {entity: sensor.hovedsoverom_humidity}
    - {entity: binary_sensor.vindu_hovedsoverom}
    show_name: false
    title: Soverom Caroline
    type: glance
  - entities:
    - {entity: light.gang_inngang}
    - {entity: sensor.entregang_temperature}
    - {entity: sensor.entregang_humidity}
    - {entity: lock.inngangsdor}
    show_name: false
    title: Gang Hovedetasje
    type: glance
  - entities:
    - {entity: light.gang_soverom}
    - {entity: sensor.gang_etg_2_temperature}
    - {entity: sensor.gang_etg_2_humidity}
    show_name: false
    title: Gang 2. Etasje
    type: glance
  - entities:
    - {entity: light.gang_kjeller}
    - {entity: sensor.kjellergang_temperature}
    - {entity: sensor.kjellergang_humidity}
    show_name: false
    title: Gang Kjeller
    type: glance
  - entities:
    - {entity: light.kjellerstue}
    - {entity: sensor.kjellerstue_temperature}
    - {entity: sensor.kjellerstue_humidity}
    show_name: false
    title: Kino
    type: glance
  - entities:
    - {entity: light.kjellerrom}
    - {entity: binary_sensor.vindu_kjellerdor}
    - {entity: binary_sensor.kjellerdor}
    show_name: false
    title: Gjesterom
    type: glance
  - entities:
    - {entity: light.ute}
    - {entity: sensor.dark_sky_temperature}
    show_name: false
    title: Ute
    type: glance
  icon: mdi:monitor-dashboard
  path: monitor
  title: Monitor
- badges: []
  cards:
  - cards:
    - cards:
      - entities: [sensor.house_voltage]
        font_size: 75
        name: Spenning
        type: custom:mini-graph-card
      - entities: [sensor.server_watts]
        font_size: 75
        name: Server
        type: custom:mini-graph-card
      type: horizontal-stack
    - cards:
      - entities: [sensor.torketrommel_watts]
        font_size: 75
        name: Tørketrommel
        type: custom:mini-graph-card
      - entities: [sensor.projector_watts]
        font_size: 75
        name: Projektor
        type: custom:mini-graph-card
      type: horizontal-stack
    - cards:
      - entities: [sensor.vaskemaskin_watts]
        font_size: 75
        name: Vaskemaskin
        type: custom:mini-graph-card
      - entities: [sensor.varmepumpe_watts]
        font_size: 75
        name: Varmepumpe
        type: custom:mini-graph-card
      type: horizontal-stack
    - cards:
      - entities: [sensor.electricity_price_tostenhagen_54]
        font_size: 75
        name: Strømpris
        type: custom:mini-graph-card
      type: horizontal-stack
    type: vertical-stack
  - entities:
    - sensor.uptime
    - entities:
      - {entity: sensor.processor_use}
      - {entity: sensor.memory_use_percent}
      - {entity: sensor.disk_use_percent_home}
      head: binary_sensor.neptune
      type: custom:fold-entity-row
    - entities: [sensor.saturn_cpu_load_total, sensor.saturn_memory_usage_real, sensor.saturn_volume_used_volume_2]
      head: binary_sensor.saturn
      type: custom:fold-entity-row
    - entities: [sensor.mercury_cpu_load_total, sensor.mercury_memory_usage_real,
        sensor.mercury_volume_used_volume_1]
      head: binary_sensor.mercury
      type: custom:fold-entity-row
    - entities: [sensor.google_wifi_uptime, sensor.google_wifi_last_restart, sensor.google_wifi_current_version,
        sensor.google_wifi_local_ip]
      head: {entity: sensor.google_wifi_status, name: Google Wifi}
      type: custom:fold-entity-row
    show_header_toggle: false
    title: Network
    type: entities
  - entities:
    - {entity: sensor.speedtest_ping}
    - {entity: sensor.speedtest_download}
    - {entity: sensor.speedtest_upload}
    show_header_toggle: false
    title: Internet
    type: entities
  - entities:
    - {entity: sensor.varmepumpe_stats, name: Varmepumpe}
    - {entity: sensor.vaskemaskin_stats, name: Vaskemaskin}
    - {entity: sensor.torketrommel_stats}
    show_header_toggle: false
    title: Utilities Stats
    type: entities
  icon: mdi:home-automation
  path: system
  title: System
- badges: []
  cards:
  - entities: [automation.caroline_night, automation.hall_lights_day, automation.hall_lights_night,
      automation.outdoor_day, automation.outdoor_night, automation.plant_lights_day,
      automation.plant_lights_night, automation.projector_started, automation.projector_stopped]
    title: Lighting
    type: entities
  - entities:
    - {entity: automation.startup_notification}
    - {entity: automation.morning_notification}
    - {entity: automation.car_battery_notification}
    - {entity: automation.mercury_offline_notification}
    - {entity: automation.saturn_offline_notification}
    title: Notifications
    type: entities
  - entities:
    - {entity: automation.utilities_heat_pump_has_started}
    - {entity: automation.utilities_heat_pump_is_done}
    - {entity: automation.utilities_washing_machine_has_started}
    - {entity: automation.utilities_washing_machine_is_done}
    title: Utilities
    type: entities
  icon: mdi:robot
  path: automation
  title: Automation
