
# Lighting
- alias: 'Plant Lights Day'
  trigger:
    platform: time
    at: '07:00:00'
  action:
    - service: switch.turn_on
      entity_id: 
        - switch.kitchen_plant
        - switch.drivhus

- alias: 'Plant Lights Night'
  trigger:
    platform: time
    at: '21:00:00'
  action:
    - service: switch.turn_off
      entity_id: 
        - switch.kitchen_plant
        - switch.drivhus

- alias: 'Caroline Night'
  trigger:
    platform: time
    at: '18:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.soverom_caroline
        brightness_pct: 60
        color_name: hotpink
    - delay: 01:30:00
    - service: light.turn_off
      data:
        entity_id: light.soverom_caroline
        transition: 1800

# Outdoor Lights
- alias: 'Outdoor Day'
  trigger:
    platform: sun
    event: sunrise
    offset: '+00:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: light.ute

- alias: 'Outdoor Night'
  trigger:
    platform: sun
    event: sunset
    offset: '+00:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.ute

# Hall lights
- alias: 'Hall Lights Day'
  trigger:
    platform: time
    at: '06:30:00'
  action:
    service: light.turn_on
    data:
        entity_id: 
          - light.gang_inngang
          - light.gang_kjeller
          - light.gang_soverom
        brightness_pct: 100

- alias: 'Hall Lights Night'
  trigger:
    platform: time
    at: '22:00:00'
  action:
    service: light.turn_on
    data:
        entity_id:
          - light.gang_inngang
          - light.gang_kjeller
          - light.gang_soverom
        brightness_pct: 30

# Home Theater Lights
- alias: "Projector Started"
  trigger:
    - platform: state
      entity_id: binary_sensor.projector
      to: 'on'
  action:
    - service: light.turn_off
      entity_id: 
        - light.hue_color_lamp_3
        - light.hue_lightstrip_plus_1
      data:
        transition: 4
    - service: light.turn_on
      data:
        entity_id: light.hue_color_lamp_2
        transition: 4
        brightness_pct: 40

- alias: "Projector Stopped"
  trigger:
    - platform: state
      entity_id: binary_sensor.projector
      to: 'off'
  action:
    - service: light.turn_on
      entity_id: 
        - light.hue_color_lamp_3
        - light.hue_lightstrip_plus_1
      data:
        transition: 4
        brightness_pct: 100
    - service: light.turn_on
      data:
        entity_id: light.hue_color_lamp_2
        transition: 4
        brightness_pct: 100
