# System
- alias: "Startup Notification"
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.mobile_app_are
      data:
        message: "Home Assistant restarted"