- platform: template
  sensors:
    projector:
      friendly_name: "Projektor"
      icon_template: mdi:projector
      value_template: >-
        {{ states('sensor.projector_watts')|float > 50 }}

    varmepumpe:
      friendly_name: "Varmepumpe"
      icon_template: mdi:radiator
      value_template: >-
        {{ states('sensor.varmepumpe_watts')|float > 20 }}

    vaskemaskin:
      friendly_name: "Vaskemaskin"
      icon_template: mdi:washing-machine
      value_template: >-
        {{ states('sensor.vaskemaskin_watts')|float > 5 }}

    motion_detected:
      friendly_name: Any motion detected
      icon_template: mdi:motion-sensor
      value_template: >-
        {{ is_state("binary_sensor.binary_sensor.stue_sensor_motion", "on")}}

    motion_detected_last_hour:
      friendly_name: Any motion detected in last hour
      icon_template: mdi:motion-sensor
      value_template: >-
        {{ is_state("binary_sensor.motion_detected", "on") }}
      delay_off: "01:00:00"

- platform: ping
  name: Saturn
  host: !secret synology_host
  count: 1
  scan_interval: 3600

- platform: ping
  name: Mercury
  host: !secret synology_host2
  count: 1
  scan_interval: 3600

- platform: ping
  name: Neptune
  host: !secret neptune_host
  count: 1
  scan_interval: 3600