- platform: template
  sensors:
    projector:
      friendly_name: "Projector"
      icon_template: mdi:projector
      value_template: >-
        {{ states('sensor.projector_effect')|float > 50 }}

- platform: ping
  name: Saturn
  host: !secret synology_host
  count: 1
  scan_interval: 3600

- platform: ping
  name: Mercury
  host: !secret synology_host2
  count: 1
  scan_interval: 3600