- platform: group
  name: Hall lights
  entities:
    - light.gang_kjeller
    - light.gang_soverom
    - light.inngang_1
    - light.inngang_2

- platform: group
  name: Living room lights
  entities:
    - light.salong_tak
    - light.spisebord_tak

- platform: group
  name: Kitchen lights
  entities:
    - light.kjokken

- platform: group
  name: Bedroom lights
  entities:
    - light.soverom

- platform: group
  name: Bedroom C lights
  entities:
    - light.soverom_caroline

- platform: group
  name: Bedroom E lights
  entities:
    - light.soverom_emilie

- platform: group
  name: Office lights
  entities:
    - light.kontor

- platform: group
  name: Home theater lights
  entities:
    - light.kino
    - light.kino_strip

- platform: group
  name: Guest room lights
  entities:
    - light.kjellerrom
    - light.kjellerrom_spot_1
    - light.kjellerrom_spot_2
    - light.kjellerrom_spot_3

- platform: group
  name: Outside lights
  entities:
    - light.hovedinngang
    - light.terrasse_1
    - light.terrasse_2
    - light.terrasse_inngang