# Bus
- platform: entur_public_transport
  name: Buss
  stop_ids:
    - !secret buss_stop

# Weather
- platform: yr
  monitored_conditions:
    - temperature
    - symbol
    - windSpeed

- platform: darksky
  api_key: !secret dark_sky_api
  language: nb
  monitored_conditions:
    - summary
    - temperature
    - hourly_summary

# System metrics
- platform: synologydsm
  name: Saturn
  host: !secret synology_host
  username: !secret synology_user
  password: !secret synology_pwd
  monitored_conditions:
    - cpu_total_load
    - memory_real_usage
    - network_up
    - network_down
    - volume_percentage_used

- platform: synologydsm
  name: Mercury
  host: !secret synology_host2
  username: !secret synology_user
  password: !secret synology_pwd
  monitored_conditions:
    - cpu_total_load
    - memory_real_usage
    - network_up
    - network_down
    - volume_percentage_used

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: memory_use_percent
    - type: processor_use

- platform: uptime
  unit_of_measurement: hours

- platform: google_wifi

- platform: template
  sensors:
    house_voltage:
      friendly_name: "Spenning"
      unit_of_measurement: 'V'
      icon_template: mdi:flash
      value_template: "{{ state_attr('switch.varmepumpe', 'voltage') }}"

    drivhus_watts:
      friendly_name: "Drivhus usage"
      unit_of_measurement: 'W'
      icon_template: mdi:flash
      value_template: "{{ state_attr('switch.drivhus', 'current_power_w') }}"

    vaskemaskin_watts:
      friendly_name: "Vaskemaskin usage"
      unit_of_measurement: 'W'
      icon_template: mdi:washing-machine
      value_template: "{{ state_attr('switch.vaskemaskin', 'current_power_w') }}"

    vaskemaskin_stats:
      friendly_name: "Vaskemaskin stats"
      icon_template: mdi:washing-machine
      value_template: >-
        {% set hours = states.sensor.hours_washing_machine_has_been_on_last_7_days.attributes.value %}
        {% set kwh = state_attr("switch.vaskemaskin", "today_energy_kwh") | float %} 
        {% set cost_today = states("sensor.electricity_price_tostenhagen_54") | float * kwh %} 
        Forbruk idag: {{ kwh }} kWh ({{ cost_today | round(2) }} kr) 
        Siste uke: {{hours}}

    vaskemaskin_today:
      friendly_name: "Forbruk idag"
      icon_template: mdi:washing-machine
      value_template: >-
        {% set kwh = state_attr("switch.vaskemaskin", "today_energy_kwh") | float %} 
        {% set cost_today = states("sensor.electricity_price_tostenhagen_54") | float * kwh %} 
        Forbruk idag: {{ kwh }} kWh ({{ cost_today | round(2) }} kr) 

    vaskemaskin_week:
      friendly_name: "Siste uke"
      icon_template: mdi:washing-machine
      value_template: >-
        {% set hours = states.sensor.hours_washing_machine_has_been_on_last_7_days.attributes.value %}
        Siste uke: {{hours}}

    torketrommel_watts:
      friendly_name: "Tørketrommel usage"
      unit_of_measurement: 'W'
      icon_template: mdi:tumble-dryer
      value_template: "{{ state_attr('switch.dryer', 'current_power_w') }}"

    torketrommel_stats:
      friendly_name: "Tørketrommel stats"
      icon_template: mdi:tumble-dryer
      value_template: >-
        {% set hours = states.sensor.hours_dryer_has_been_on_last_7_days.attributes.value %}
        {% set kwh = state_attr("switch.dryer", "today_energy_kwh") | float %} 
        {% set cost_today = states("sensor.electricity_price_tostenhagen_54") | float * kwh %} 
        {{hours}} - {{ cost_today | round(2) }} kr - {{ kwh }} kWh

    projector_watts:
      friendly_name: "Projektor usage"
      unit_of_measurement: 'W'
      icon_template: mdi:projector
      value_template: "{{ state_attr('switch.projector', 'current_power_w') }}"

    varmepumpe_watts:
      friendly_name: "Varmepumpe usage"
      unit_of_measurement: 'W'
      icon_template: mdi:radiator
      value_template: "{{ state_attr('switch.varmepumpe', 'current_power_w') }}"

    varmepumpe_stats:
      friendly_name: "Varmepumpe stats"
      icon_template: mdi:radiator
      value_template: >-
        {% set hours = states.sensor.hours_heat_pump_has_been_on_last_7_days.attributes.value %}
        {% set kwh = state_attr("switch.varmepumpe", "today_energy_kwh") | float %} 
        {% set cost_today = states("sensor.electricity_price_tostenhagen_54") | float * kwh %} 
        {{hours}} - {{ cost_today | round(2) }} kr - {{ kwh }} kWh

    server_watts:
      friendly_name: "Server usage"
      unit_of_measurement: 'W'
      icon_template: mdi:flash
      value_template: "{{ state_attr('switch.server_rack', 'current_power_w') }}"

- platform: history_stats
  name: Hours TV has been on last 7 days
  entity_id: media_player.stue_tv
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours washing machine has been on last 7 days
  entity_id: binary_sensor.vaskemaskin
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours dryer has been on last 7 days
  entity_id: binary_sensor.torketrommel
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours heat pump has been on last 7 days
  entity_id: binary_sensor.varmepumpe
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours projector has been on last 7 days
  entity_id: binary_sensor.projector
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"