# Bus
- platform: entur_public_transport
  name: Buss
  stop_ids:
    - !secret buss_stop

# Weather
- platform: yr
  monitored_conditions:
    - temperature
    - symbol
    - windSpeed

- platform: darksky
  api_key: !secret dark_sky_api
  language: nb
  monitored_conditions:
    - summary
    - temperature
    - hourly_summary

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: memory_use_percent
    - type: processor_use

- platform: uptime
  unit_of_measurement: hours

- platform: google_wifi

- platform: template
  sensors:
    house_voltage:
      friendly_name: "Spenning"
      unit_of_measurement: 'V'
      icon_template: mdi:flash
      value_template: "{{ state_attr('switch.varmepumpe', 'voltage') }}"

    drivhus_watts:
      friendly_name: "Drivhus usage"
      unit_of_measurement: 'W'
      icon_template: mdi:flash
      value_template: "{{ state_attr('switch.drivhus', 'current_power_w') }}"

    vaskemaskin_watts:
      friendly_name: "Vaskemaskin usage"
      unit_of_measurement: 'W'
      icon_template: mdi:washing-machine
      value_template: "{{ state_attr('switch.vaskemaskin', 'current_power_w') }}"

    torketrommel_watts:
      friendly_name: "Tørketrommel usage"
      unit_of_measurement: 'W'
      icon_template: mdi:tumble-dryer
      value_template: "{{ state_attr('switch.dryer', 'current_power_w') }}"

    projector_watts:
      friendly_name: "Projektor usage"
      unit_of_measurement: 'W'
      icon_template: mdi:projector
      value_template: "{{ state_attr('switch.projector', 'current_power_w') }}"

    varmepumpe_watts:
      friendly_name: "Varmepumpe usage"
      unit_of_measurement: 'W'
      icon_template: mdi:radiator
      value_template: "{{ state_attr('switch.varmepumpe', 'current_power_w') }}"

    server_watts:
      friendly_name: "Server usage"
      unit_of_measurement: 'W'
      icon_template: mdi:flash
      value_template: "{{ state_attr('switch.server_rack', 'current_power_w') }}"

- platform: history_stats
  name: Hours TV has been on last 7 days
  entity_id: media_player.stue_tv
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours washing machine has been on last 7 days
  entity_id: binary_sensor.vaskemaskin
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours dryer has been on last 7 days
  entity_id: binary_sensor.torketrommel
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours heat pump has been on last 7 days
  entity_id: binary_sensor.varmepumpe
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"

- platform: history_stats
  name: Hours projector has been on last 7 days
  entity_id: binary_sensor.projector
  state: "on"
  type: time
  duration:
    days: 7
  end: "{{ now() }}"